#!/bin/bash

#var_management
from_dir="./tests/pond/"
to_dir="./tests/redirect/"
del_flag=0
transfers_done=0
folders_made=0
#########################|

#flag manager
while getopts 'd' OPTION ;
do
    case "$OPTION" in
        d) del_flag=1
    esac
done
#########################|


#welcome Label
echo "-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^"
echo "|                    Heyyy! Welcome TO t0rvalds                      |"
echo "-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^"
#############################################################################|

#main_program
for i in `find $from_dir -type f | sed -n '/\..*[^\/]\..*$/p'  ` ;
do
    #echo $i
    name=`echo $i | awk 'BEGIN{FS="/"} {print $NF}'`
    ext=`echo $i | awk 'BEGIN{FS="."} {print $NF}'`
    if [ ! -d $to_dir ]
    then
        echo "t0rvalds : the destination folder doesn't exists, making"
        mkdir $to_dir
    fi

    if [ -d $to_dir/ext_$ext ] ;
    then
        if [ -f $to_dir/ext_$ext/$name ]
        then
            ddmmyyyy=`stat $i | sed -n '/Birth/p' | awk 'BEGIN{FS=" "}{print $2}' | awk 'BEGIN{FS="-"} {print $3$2$1}'`
            mv $to_dir/ext_$ext/$name $to_dir/ext_$ext/dummy
            cp $i $to_dir/ext_$ext
            mv $to_dir/ext_$ext/$name $to_dir/ext_$ext/$name"_"$ddmmyyyy
            mv $to_dir/ext_$ext/dummy $to_dir/ext_$ext/$name
            echo "t0rvalds : the file $name already exists, copying as $name"_"$ddmmyyyy "
        else
        echo "t0rvalds : copying $name to address $to_dir""ext_$ext"
        cp $i $to_dir/ext_$ext
        fi
        let "transfers_made=transfers_made+1"
        echo $i >> .files_moved
    else
        echo "t0rvalds : making directory ext_$ext"
        mkdir $to_dir/ext_$ext
        let "folders_made=folders_made+1"
        echo "t0rvalds : copying $name to folder ext_$ext"
        cp $i $to_dir/ext_$ext
        let "transfers_made=transfers_made+1"
        echo $i >> .files_moved
    fi
    echo $to_dir/ext_$ext >> .folder_list
done
#######################################################################################################################|

#log generation
echo -e "-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^"
echo "|                              The Log                               |"
echo "-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^"
echo "Total New Folders Made : $folders_made"
echo "Total Moves : $transfers_made"
for i in `cat .folder_list | sort |uniq`;
do
    folder_name=`echo $i | awk 'BEGIN{FS="/"} {print $NF}'`
    echo "The folder $folder_name has `ls $i | wc -l` files."
done
if [ -f .folder_list ] ;
then
    rm .folder_list
fi
##################################################################################|

#-d option handler
if [ $del_flag = 1 ]
then
    for i in .files_moved ;
    do
        rm $i
    done
fi
##################################################################################|

#bye
echo "-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^"
echo "|                                Bye!                                |"
echo "-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^-^"
##################################################################################|
